# docker-compose.yml
services:
  ai-butler:
    # 1) Para desarrollo: construye la imagen localmente
    build:
      context: .
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    # 2) Para producción: si ya tienes la imagen en GHCR, coméntalo
    # image: ghcr.io/Maux0290/ai-butler-mvp:latest

    container_name: ai-butler-mvp
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./ai_butler.db:/app/ai_butler.db
      - faiss_index:/app/faiss_index

volumes:
  faiss_index:

