version: "3.8"
services:
  ai-butler:
    build:
      context: .
      dockerfile: Dockerfile_produccion
    container_name: ai-butler-prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs          # logs persistentes
      - ./data:/app/data          # carpeta persistente para BD, archivos
    environment:
      - TZ=Europe/Madrid          # ajusta tu zona horaria si lo deseas


