# docker-compose.yml (en la raíz del proyecto)

services:
  ai-butler:
    build: .
    image: maux0290/ai-butler-mvp:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data      # <— bind-mount local → contenedor

