version: 1
disable_existing_loggers: false
formatters:
  default:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
handlers:
  file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: /app/logs/ai_butler.log
    encoding: utf8
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
loggers:
  uvicorn:
    level: INFO
    handlers: [file, console]
    propagate: no
  uvicorn.error:
    level: INFO
    handlers: [file, console]
    propagate: no
  uvicorn.access:
    level: INFO
    handlers: [file, console]
    propagate: no
  ai_butler:
    level: INFO
    handlers: [file, console]
    propagate: no
  fastapi:
    level: INFO
    handlers: [file, console]
    propagate: no
root:
  level: INFO
  handlers: [file, console]



