# .github/workflows/ci-docker.yml
name: CI / Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          # baja todo a minúsculas:
          tags: |
            ghcr.io/maux0290/ai-butler-mvp:latest
            ghcr.io/maux0290/ai-butler-mvp:${{ github.sha }}
        # si quisieras usar secrets para Docker Hub en su lugar:
        # secrets:
        #   username: ${{ secrets.DOCKERHUB_USERNAME }}
        #   password: ${{ secrets.DOCKERHUB_PASSWORD }}