name: CI / Build & Push Docker Image

on:
  push:
    branches: [ produccion ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile_produccion
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
            ghcr.io/maux0290/ai-butler-produccion:latest
            ghcr.io/maux0290/ai-butler-produccion:${{ github.sha }}

